#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/sourcezap
user=_sourcezap
repodir="${1}"

##
# functions
# shellcheck source=/dev/null
. "${libexec}"/functions/print.sh

##
# main
if [ "$(id -u)" = "0" ]; then
    printerr "you must be a user other than root"
    exit 1
fi

if ! "${libexec}"/scripts/is-sourcezap-member; then
   printerr "$(id -un) is not a member of _sourcezap"
   exit 1
fi

if [ ! -e "${repodir}" ]; then
    printerr "try 'sourcezap clone' instead"
    exit 1
fi

cd "${repodir}"
doas -n \
     -u "${user}" \
     /bin/sh
