#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/sourcezap
giturl=$1
gitdir=$2
branch=$3

##
# functions
gitexec()
{
    "${libexec}"/util/gitexec "${1}"
}

printok()
{
    "${libexec}"/utils/printok "${1}"
}

printerr()
{
    "${libexec}"/utils/printerr "${1}"
}

##
# main
if [ "$(id -u)" = "0" ]; then
    printerr "you must be a user other than root"
    exit 1
fi

if ! "${libexec}"/utils/issourcezap-member > /dev/null >2&1; then
    printerr "$(id -un) is not a member of _sourcezap"
    exit 1
fi

if [ -e "${gitdir}/.git" ]; then
    printerr "try 'sourcezap pull' instead"
    exit 1
fi

set -x
gitexec "clone ${giturl} ${gitdir}"
cd "${gitdir}"
gitexec "config core.filemode off"
gitexec "checkout -t origin/${branch}"
set +x
printok "clone complete"
