#!/bin/sh
set -e

#
# globals
#
libexec="$(dirname "$0")"/..
rad="${libexec}"/scripts/rad
git="${libexec}"/scripts/git
radid=$1
radnid=$2
repodir=$3
branch=$4

#
# functions
#
. "${libexec}"/functions/print.sh

#
# main
#
if [ -e "${repodir}"/.git ]; then
    printerr "repository has already been cloned"
    exit 1
fi

"${rad}" clone "${radid}" --seed "${radnid}" "${repodir}"
cd "${repodir}"
"${git}" config core.filemode off
printok "clone complete"
