#!/bin/sh
set -e

#
# variable
#
libexec="$(dirname "$0")"/..
repodir="${1}"

#
# functions
#
. "${libexec}"/functions/print.sh

#
# main
#
if [ ! -e "${repodir}" ]; then
    printerr "try 'sourcezap clone' instead"
    exit 1
fi

cd "${repodir}"
"${libexec}"/scripts/mdo
