#!/bin/sh
set -e

#
# globals
#
libexec="$(dirname "$0")"/..

#
# functions
#
. "${libexec}"/functions/print.sh
. "${libexec}"/functions/mdo.sh

#
# main
#
sourcezap_rules=$(get_sourcezap_rules "${libexec}")
system_rules=$(get_system_rules)
if [ -z "${system_rules}" ]; then
    printok "disabled"
    exit 1
fi
if is_rule_enabled "${system_rules}" "${sourcezap_rules}"; then
    printok "enabled"
    exit 0
fi
printok "disabled"
exit 1
