#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/sourcezap
gitdir=$1

##
# functions
git()
{
    "${libexec}"/utils/git "${@}"
}

printok()
{
    "${libexec}"/utils/printok "${1}"
}

printerr()
{
    "${libexec}"/utils/printerr "${1}"
}

##
# main
if [ "$(id -u)" = "0" ]; then
    printerr "you must be a user other than root"
    exit 1
fi

if ! "${libexec}"/utils/issourcezap-member > /dev/null 2>&1; then
    printerr "$(id -un) is not a member of _sourcezap"
    exit 1
fi

if [ ! -e "${gitdir}/.git" ]; then
    set +x
    printerr "try 'sourcezap clone' instead"
    exit 1
fi

set -x
cd "${gitdir}"
branch=$(git "branch --show-current")
git pull --rebase origin "${branch}"
set +x
printok "pull complete"
