#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/sourcezap
git=$(which git)
mask=$("${libexec}"/scripts/get-default-umask)

##
# main
doas -n \
     -u _sourcezap \
     /bin/sh -c "umask ${mask}; ${git} ${*}"
