#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/sourcezap
mask=$("${libexec}"/scripts/get-default-umask)

##
# main
install -o root \
        -g _sourcezap \
        -m "${mask}" \
        -v \
        "${@}"
