#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/sourcezap
user="_sourcezap"

##
# functions
# shellcheck source=/dev/null
. "${libexec}"/functions/print.sh

##
# main
if ! id -u "${user}" > /dev/null 2>&1; then
    pw useradd \
       -n "${user}" \
       -c "sourcezap user" \
       -m \
       -M "$("${libexec}"/scripts/get-default-umask)" \
       -s /sbin/nologin
fi
printok "user setup complete"
