#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/sourcezap
user="_sourcezap"

##
# functions
. "${libexec}"/functions/print.sh

##
# main
if id -u "${user}" > /dev/null 2>&1; then
   printok "${user} user exists"
else
    pw useradd \
       -n "${user}" \
       -c "sourcezap user" \
       -m \
       -s /sbin/nologin
    chmod u=rwX,g=rX,o= /home/"${user}"/
    printok "${user} user created"
fi
