#!/bin/sh
#
#

# PROVIDE: sourcezap
# REQUIRE: FILESYSTEMS mountcritlocal sysctl
# KEYWORD: shutdown

. /etc/rc.subr

name="sourcezap"
desc="sourcezap mac_do(4) manager"
rcvar="sourcezap_enable"
command="/usr/local/bin/sourcezap"
required_files="${command}"
stop_cmd="sourcezap_stop"
start_cmd="sourcezap_start"
status_cmd="sourcezap_status"

sourcezap_start()
{
    "${command}" apply
}

sourcezap_stop()
{
    "${command}" unapply
}

sourcezap_status()
{
    "${command}" status
}

load_rc_config $name

run_rc_command "$1"
