#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../../..)}
libexec="${localbase}"/libexec/sourcezap
git="${libexec}"/utils/git/run
gitdir=$1
commit=$2

##
# functions
. "${libexec}"/functions.sh

##
# main
cd "${gitdir}"
"${git}" diff -l0 --name-only --diff-filter=D "${commit}" "HEAD"
