#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/sourcezap
gitdir=$1
commit=$2

##
# functions
git()
{
    "${libexec}"/utils/git/run "${@}"
}

##
# main
cd "${gitdir}"
git diff -l0 --name-only --diff-filter=A "${commit}" "HEAD"
git diff -l0 --name-only --diff-filter=M "${commit}" "HEAD"
