#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/sourcezap
gitdir=$1

##
# functions
git()
{
    "${libexec}"/utils/git "${1}"
}

##
# main
cd "${gitdir}"
git rev-parse HEAD
