.Dd May 2023
.Dt SOURCEZAP 8
.Os
.Sh NAME
.Nm sourcezap
.Nd manages a copy of the HardenedBSD source tree
.Sh SYNOPSIS
.br
.Nm sourcezap setup
.Nm sourcezap teardown
.Nm sourcezap clone
.Nm sourcezap pull
.Nm sourcezap sh
.Nm sourcezap install
.Nm sourcezap rm
.Sh DESCRIPTION
.Nm sourcezap
manages a copy of the HardenedBSD source tree.
The copy of the source tree is maintained by members of
the '_sourcezap' group, and a copy of the source tree
can be installed into /usr/src/ by root.
.Sh SETUP
.sp
.sp
.Nm sourcezap setup
.br
Setup sourcezap for the first time
.br
This command requires root privileges
.Pp
.Nm sourcezap teardown
.br
Reverse the changes made by 'sourcezap setup'
.br
This command requires root privileges
.Pp
.Nm pw groupmod _sourcezap -m <user>
.br
Append a user to the '_sourcezap' group
.br
This command requires root privileges
.Pp
.Sh GENERAL
.sp
.sp
.Nm sourcezap clone
.br
Clone the HardenedBSD source tree into /home/_sourcezap/src/
.br
This command is delegated to the '_sourcezap' user and
limited to members of the '_sourcezap' group
.Pp
.Nm sourcezap pull
.br
Pull updates into /home/_sourcezap/src/
.br
This command is delegated to the '_sourcezap' user and
limited to members of the '_sourcezap' group
.Pp
.Nm sourcezap sh
.br
Run /bin/sh within /home/_sourcezap/src/
.br
This command is delegated to the '_sourcezap' user and
limited to members of the '_sourcezap' group
.Pp
.Nm sourcezap rm
.br
Remove the contents of /usr/src/ and /home/_sourcezap/src/
.br
This command requires root privileges
.Pp
.Nm sourcezap install
.br
Install /home/_sourcezap/src/ into /usr/src/
.br
This command requires root privileges
.br
.Sh ENVIRONMENT
.sp
.sp
.Nm SOURCEZAP_CLONEURL
.br
The URL of a git repository
.br
Default: https://github.com/HardenedBSD/HardenedBSD.git/
.sp
.Nm SOURCEZAP_INSTALLDIR
.br
The directory where the source tree will be installed
.br
Default: /usr/src/
.sp
.Sh AUTHORS
The
.Nm sourcezap
utility and this manual page were written by
0x1eef <0x1eef@protonmail.com>.
