#!/bin/sh
set -e

##
# variables
libexec=$(dirname "$0")
localbase=${LOCALBASE:-/usr/local}
git="${localbase}"/bin/git
gitdir="$1"
mode="u=rwX,g=rX,o="

##
# functions
gitexec()
{
    doas -n -u _sourcezap \
         /bin/sh -c "umask ${mode}; ${git} ${1}"
}

##
# main
if ! "${libexec}"/issourcezap-member; then
    echo "[x] This command must be run by a member of the '_sourcezap' group"
    exit 1
fi

if [ ! -e "${gitdir}/.git" ]; then
    set +x
    echo "[x] ${gitdir} is not a valid git repository."
    echo "[x] Try: sourcezap clone"
    exit 1
fi

set -x
cd "${gitdir}"
branch=$(gitexec "branch --show-current")
gitexec "pull --rebase origin ${branch}"
