#!/bin/sh
set -e

##
# variables
gitdir=$1
installdir=$2

##
# functions
erase()
{
    dir="${1}"
    printf "%s  " "${dir}"
    find "${dir}" \
        -maxdepth 1 \
        \! -name "." \
        \! -name ".." \
        \! -name "src" \
        -exec printf . \; \
        -exec rm -rf "{}" \;
    echo
}

##
# main
if [ "$(id -u)" != "0" ]; then
    echo "[-] This command must be run by root"
    exit 1
fi

printf "Choose an option:\n"
printf "1 Erase %s\n" "${gitdir}"
printf "2 Erase %s\n" "${installdir}"
printf "3 Erase both (%s and %s)\n" "${gitdir}" "${installdir}"
printf "4 Do nothing\n"
printf "1-4: "
while true; do
    read -r r
    if [ "${r}" = "1" ]; then
        erase "${gitdir}"
        exit
    elif [ "${r}" = "2" ]; then
        erase "${installdir}"
        exit
    elif [ "${r}" = "3" ]; then
        erase "${gitdir}"
        erase "${installdir}"
        exit
    elif [ "${r}" = "4" ]; then
        printf "[-] Exiting... \n"
        exit
    else
        printf "[x] %s is not a valid option.\n" "${r}"
        printf "1-4: "
    fi
done
